apiVersion: v1
kind: Service
metadata:
  name: {{ include "orbit.fullname" . }}
  labels:
    {{- include "orbit.componentLabels" (list . "web") | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "orbit.componentSelectorLabels" (list . "web") | nindent 4 }}
